spring:
  application:
    name: BackendSpring

  datasource:
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

#  profiles:
#    active: prod

app:
  message: "Hello from default profile"




